### ISSUE TITLE
TypeError: this._select is not a function

### ISSUE THREAD

**Issue by jolic** [lirantal/is-website-vulnerable#26]
every ```npx is-website-vulnerable https://......``` ends with an error:

```
npx: Installierte 270 in 19.787s
✔ Set up completed in 1.56 seconds!
[==  ] Auditing...
{ TypeError: this._select is not a function
    at PluralRules.select (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/intl-pluralrules/factory.js:143:21)
    at PluralFormat.getOption (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/intl-messageformat/dist/compiler.js:161:38)
    at formatPatterns (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/intl-messageformat/dist/core.js:69:43)
    at IntlMessageFormat.format (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/intl-messageformat/dist/core.js:139:24)
    at _formatIcuMessage (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/lib/i18n/i18n.js:293:37)
    at _resolveIcuMessageInstanceId (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/lib/i18n/i18n.js:424:29)
    at replaceInObject (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/lib/i18n/i18n.js:452:55)
    at replaceInObject (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/lib/i18n/i18n.js:465:9)
    at replaceInObject (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/lib/i18n/i18n.js:465:9)
    at Object.replaceIcuMessageInstanceIds (~/.npm/_npx/20132/lib/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/lib/i18n/i18n.js:472:3) friendlyMessage: undefined }

```

## Expected Behavior

It works.

## Current Behavior

It throws the above error.

## Your Environment

- Node.js v12.3.1, v8.16.1
- Mac Mojave 10.14.6

**Comment by lirantal** [comment]
@jolic can you try executing it again once the new version get released? it should be published in a couple of minutes
